; ESP32 GPS-disciplined NTP server
; Build:   pio run
; Flash:   pio run -t upload
; Monitor: pio device monitor

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
